# Variable Group 'Test' was defined in the Variables tab
# Variable Group 'FE variable' was defined in the Variables tab
trigger:
  branches:
    include:
    - releases/*
    - dev
    - main
  batch: true
name: $(SourceBranchName)_$(Date:ddMMyyyy)$(Rev:.r)
variables:
  GIT_PAT: $(gitPat)
  AZURE_PAT: $(azurePass)
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: U_W
  displayName: Build Ubuntu and Window
  pool:
    name: Builder
  steps:
  - checkout: self
  - task: mirror-git-repository-vsts-task@1
    inputs:
      sourceGitRepositoryUri: '$(Build.Repository.Uri)'
      sourceVerifySSLCertificate: false
      destinationGitRepositoryUri: 'https://github.com/sonntuet1997/gIqtree'
      sourceGitRepositoryPersonalAccessToken: $(AZURE_PAT)
      destinationGitRepositoryPersonalAccessToken: $(GIT_PAT)
  - task: CmdLine@2
    displayName: Build
    inputs:
      script: |
        ls 
        rm -Rf dist
        rm -Rf uw
        ./build.sh
        rm -Rf dist/linux-unpacked
        rm -Rf dist/win-unpacked
        mkdir uw
        find ./dist -name '*.exe' -exec cp -prv '{}' "./uw/" ";"
        find ./dist -name '*.AppImage' -exec cp -prv '{}' "./uw/" ";"
      workingDirectory: $(System.DefaultWorkingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Ubuntu And Window'
    inputs:
      PathtoPublish: uw
      ArtifactName: ubuntu-and-windown

- job: MAC
  displayName: Build MacOS
  pool:
    name: MAC
  steps:
  - checkout: self
  - task: CmdLine@2
    displayName: Build
    inputs:
      script: |
        ls 
        rm -Rf dist
        rm -Rf mac
        yarn
        yarn build:mac
        mkdir mac
        find ./dist -name '*.dmg' -exec cp -prv '{}' "./mac/" ";"
      workingDirectory: $(System.DefaultWorkingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: MacOS'
    inputs:
      PathtoPublish: mac
      ArtifactName: mac

